version: "3.7"

services:
  nginx-proxy:
    image: nginx:1.19
    ports:
      - target: 80
        published: 80
        mode: ingress
    networks:
      - api
      - imageproxy
      - auth-server
    environment:
      GATEWAY_URL: http://api-gateway:4000
      IMAGEPROXY_URL: http://imageproxy:8080
      AUTH_SERVER_URL: http://auth-server:4000
      API_SERVER_NAME: $API_HOST
      AUTH_SERVER_NAME: $AUTH_SERVER_HOST
      IMAGEPROXY_SERVER_NAME: $IMAGEPROXY_HOST
    volumes:
      - ./nginx/proxy/templates:/etc/nginx/templates
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  api-gateway:
    image: ghcr.io/bo2kshelf/api-gateway:develop@sha256:9e7cdbb5cf4476b246817e681ced9096c6340bdda05f2f0f6ff92cd16221b1b8
    networks:
      - api
    environment:
      PORT: 4000
      BOOKS_API_URL: http://neo4j-api:4000/graphql
      BOOKCOVER_API_URL: http://bookcover-api:4000/graphql
      SEARCH_API_URL: http://search-api:4000/graphql
      USERS_API_URL: http://users-api:4000/graphql
      GRAPHQL_COOKIE_TOKEN_KEY: graphql_access_token
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  imageproxy:
    image: willnorris/imageproxy
    networks:
      - imageproxy
    environment:
      IMAGEPROXY_CACHE: redis://imageproxy-redis:6379
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  imageproxy-redis:
    image: redis:6
    networks:
      - imageproxy
    volumes:
      - imageproxy-redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  bookcover-api:
    image: ghcr.io/bo2kshelf/bookcover-api:develop@sha256:b59cddac6444f64b41f057b925497ec1e5e346f5fa389e4625ab22f4e3369e4f
    networks:
      - api
      - bookcover
      - imageproxy
    ports:
      - published: ${BOOKCOVER_API_PORT}
        target: 4000
        mode: ingress
    environment:
      PORT: 4000
      RAKUTEN_APPLICATION_ID: $RAKUTEN_APPLICATION_ID
      RAKUTEN_APPLICATION_SECRET: $RAKUTEN_APPLICATION_SECRET
      IMAGEPROXY_BASE_URL: http://${IMAGEPROXY_HOST}
      REDIS_CACHE_HOST: bookcover-redis
      REDIS_CACHE_PORT: 6379
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  bookcover-redis:
    image: redis:6
    networks:
      - bookcover
    volumes:
      - bookcover-redis-data:/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  neo4j-api:
    image: ghcr.io/bo2kshelf/neo4j-api@sha256:76448c9672e5525a6741852738fc937a2787ff6565ed2d9c4f67b7a1071b72fd
    networks:
      - api
      - neo4j
    ports:
      - published: ${NEO4J_API_PORT}
        target: 4000
        mode: ingress
    environment:
      PORT: 4000
      NEO4J_URL: bolt://neo4j-neo4j:7687
      NEO4J_USERNAME: $NEO4J_NEO4J_USER
      NEO4J_PASSWORD: $NEO4J_NEO4J_PASSWORD
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  neo4j-neo4j:
    image: neo4j:4.2
    networks:
      - neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_NEO4J_USER}/${NEO4J_NEO4J_PASSWORD}
      NEO4JLABS_PLUGINS: '["apoc"]'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      NEO4J_apoc_import_file_use__neo4j__config: "true"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  users-api:
    image: ghcr.io/bo2kshelf/users-api:develop@sha256:1f7072042c6e65a703d5f08a7d1463cbcbfdb36aab00a6fd0ffb987148f49541
    networks:
      - api
      - users
      - imageproxy
    ports:
      - published: ${USERS_API_PORT}
        target: 4000
        mode: ingress
    environment:
      PORT: 4000
      IMAGEPROXY_BASE_URL: http://${IMAGEPROXY_HOST}
      GITHUB_CLIENT_ID: $GITHUB_CLIENT_ID
      GITHUB_CLIENT_SECRET: $GITHUB_CLIENT_SECRET
      JWT_SECRET: $USERS_JWT_SECRET
      PRISMA_DATABASE_URL: mysql://${USERS_MYSQL_USER}:${USERS_MYSQL_PASSWORD}@users-mysql:3306/${USERS_MYSQL_DATABASE}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  users-mysql:
    image: mysql:8.0
    networks:
      - users
    environment:
      MYSQL_ROOT_PASSWORD: $USERS_MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $USERS_MYSQL_DATABASE
      MYSQL_USER: $USERS_MYSQL_USER
      MYSQL_PASSWORD: $USERS_MYSQL_PASSWORD
    volumes:
      - users-api-mysql-data:/var/lib/mysql
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 10s
      timeout: 20s
      retries: 10
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  search-api:
    image: ghcr.io/bo2kshelf/search-api:develop
    networks:
      - api
      - search
    ports:
      - published: ${SEARCH_API_PORT}
        target: 4000
        mode: ingress
    environment:
      ELASTICSEARCH_NODE_URI: http://search-elasticsearch:9200
      ELASTICSEARCH_BOOKS_INDEX: books
      ELASTICSEARCH_AUTHORS_INDEX: authors
      ELASTICSEARCH_SERIES_INDEX: series
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        order: start-first

  search-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.9.3
    networks:
      - search
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - search-elasticsearch:/usr/share/elasticsearch/data
    networks:
      - search
    healthcheck:
      test: "curl --fail http://localhost:9200 || exit 1"
      interval: 2s
      timeout: 60s
      retries: 300

  auth-server:
    image: ghcr.io/bo2kshelf/auth-server:develop@sha256:64f07fe3863d40d5866e31fde0a3a21cb543f447b582499d3d49bc0ebf0ebda7
    environment:
      PORT: 4000
      USER_API_ENDPOINT: http://users-api:4000
      JWT_SECRET: ${AUTH_SERVER_JWT_SECRET}
      SESSION_SECRET: ${AUTH_SERVER_SESSION_SECRET}
      SESSION_MONGO_URI: mongodb://${AUTH_SERVER_MONGO_USERNAME}:${AUTH_SERVER_MONGO_PASSWORD}@auth-server-mongo:27017/${AUTH_SERVER_MONGO_DATABASE}?authSource=admin
      PRISMA_DATABASE_URL: postgresql://${AUTH_SERVER_POSTGRES_USERNAME}:${AUTH_SERVER_POSTGRES_PASSWORD}@auth-server-postgresql:5432/${AUTH_SERVER_POSTGRES_DATABASE}
    ports:
      - published: ${AUTH_SERVER_PORT}
        target: 4000
        mode: ingress
    networks:
      - auth-server
      - users

  auth-server-mongo:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${AUTH_SERVER_MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${AUTH_SERVER_MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${AUTH_SERVER_MONGO_DATABASE}
    networks:
      - auth-server
    volumes:
      - auth-server-mongo-data:/data/db

  auth-server-postgresql:
    image: postgres:13.2
    ports:
      - published: 5432
        target: 5432
    environment:
      POSTGRES_USER: ${AUTH_SERVER_POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_SERVER_POSTGRES_PASSWORD}
      POSTGRES_DB: ${AUTH_SERVER_POSTGRES_DATABASE}
    networks:
      - auth-server
    volumes:
      - auth-server-postgresql-data:/var/lib/postgresql/data

volumes:
  imageproxy-redis-data:
  users-mysql-data:
  bookcover-mysql-data:
  bookcover-redis-data:
  neo4j-neo4j-data:
  neo4j-neo4j-plugins:
  search-elasticsearch:
  auth-server-mongo-data:
  auth-server-postgresql-data:

networks:
  api:
    driver: overlay
    attachable: true

  users:
    driver: overlay
    attachable: true

  neo4j:
    driver: overlay
    attachable: true

  bookcover:
    driver: overlay
    attachable: true

  search:
    driver: overlay
    attachable: true

  imageproxy:
    driver: overlay
    attachable: true

  auth-server:
    driver: overlay
    attachable: true
